name: build

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  build-publish:
    runs-on: ubuntu-20.04
    env:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Setup node 18
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: yarn
      - run: yarn
      - run: yarn netlify link --id $NETLIFY_SITE_ID
      - run: yarn netlify build
      - run: yarn netlify deploy --prod
